package de.informaticum.xjc.util;

import java.io.PrintWriter;
import java.io.StringWriter;
import com.sun.codemodel.JFormatter;
import com.sun.codemodel.JGenerable;

public enum Printify {
    ;

    /**
     * @param $component
     *            the requested code component
     * @return the according Java code (generated by the component itself)
     * @see JGenerable#generate(JFormatter)
     */
    public static final String render(final JGenerable $component) {
        final var out = new StringWriter();
        $component.generate(new JFormatter(new PrintWriter(out)));
        return out.toString();
    }

}
